 /* A view for Holders report segregated by marital status. */
SELECT 1 AS id,
    count(*) AS total_registered_holders,
    count(*) FILTER (WHERE ((cb_holder_vw_social_tenure_relationship.holder_marital_status)::text = 'Unmarried'::text)) AS unmarried_holders,
    count(*) FILTER (WHERE ((cb_holder_vw_social_tenure_relationship.holder_marital_status)::text = 'Married'::text)) AS married_holders,
    concat('Generated by ', CURRENT_USER, ' on ', LOCALTIMESTAMP(0)) AS user_time_text
   FROM cb_holder_vw_social_tenure_relationship